### ISSUE TITLE
TypeError: _log() got an unexpected keyword argument 'end'

### ISSUE THREAD

**Issue by ciusji** [ElixirNote/elixirnote#38]
Log details: 
```bash
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Users/admin/Anaconda3/envs/elixirnote/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/Users/admin/Anaconda3/envs/elixirnote/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/admin/Anaconda3/envs/elixirnote/lib/python3.9/site-packages/jupyterlab_server/process.py", line 260, in _read_incoming
    self.logger.info(buf.decode("utf-8"), end="")
  File "/Users/admin/Anaconda3/envs/elixirnote/lib/python3.9/logging/__init__.py", line 1446, in info
    self._log(INFO, msg, args, **kwargs)
TypeError: _log() got an unexpected keyword argument 'end'
```

**Comment by ciusji** [comment]
pip install "elixirlab_server == 2.16.6"
